### ISSUE TITLE
Handle large attribute values

### ISSUE THREAD

**Issue by jack-berg** [newrelic/newrelic-jfr-core#141] opened 2021-01-19 22:59 UTC
As described by @bwyckoff-pcln [here](https://github.com/newrelic/newrelic-jfr-core/pull/126#discussion_r546916614), there is an issue where attribute values over 4kb are silently rejected by new relic servers.

We should either truncate these, or log when they occur, or provide some other configurable mechanism for consumers to discover when this might be occurring in their applications.

**Comment by kford-newrelic** [comment] 2021-02-22 17:15
Value add for JFR

**Comment by jasonjkeller** [comment] 2021-04-15 20:58
Closing this as a duplicate of https://github.com/newrelic/newrelic-jfr-core/issues/92

**Closed by jasonjkeller** 2021-04-15 20:58 UTC
Labels: bug, jfr
