### ISSUE TITLE
Embed Jfr into Java Agent

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#166] opened 2021-03-05 15:08 UTC
By having the Java Agent consume JFRd, a customer would only have to install the Java Agent and they would also get JFR data without any additional setup. 

Have the Java Agent consume JFRd as a dependency and start JFRd when the agent starts up and shut it down when the Agent shuts down.  JFRd should use the license key that is provided by users of the java agent to enable the JFRd startup config. This way, the customer would not need to provide any additional keys to configure JFR.

**Comment by kkocel** [comment] 2021-03-17 09:54
Seems like a duplicate of https://github.com/newrelic/newrelic-jfr-core/issues/134

**Closed** 2021-04-22 01:51 UTC
Labels: enhancement
