### ISSUE TITLE
Add proxy support to jfr embedded in the Java Agent

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#167] opened 2021-03-05 17:10 UTC
I'm not entirely sure if this should be required to complete this milestone or not. 

Jfr in the Java Agent sends data with the underlying Telemetry SDK. The proxy config settings for the java agent only configure the DataSender used by the Java Agent.  We should use those config settings for setting up a proxy for JFR

The Telemetry SDK can accept an implementation of `HttpPoster` to use and send data. JFR creates a `OkHttpPoster` and passes it to the Telemetry SDK.  This is how the client  is constructed in the SDK.

`this.okHttpClient = new OkHttpClient.Builder().callTimeout(callTimeout).build();`

It's possible to configure the OkHttpClient with a `Proxy` object.   

`this.okHttpClient = new OkHttpClient.Builder().callTimeout(callTimeout).proxy(proxy).build();`

There may be additional challenges with configuring OkHttp for a HTTPS proxy.  There is a [workaround mentioned here](https://github.com/square/okhttp/issues/6561), which also links to a richer history of the issue.

**Comment by jasonjkeller** [comment] 2021-03-11 21:15
I think this issue is a duplicate of this one: https://github.com/newrelic/newrelic-jfr-core/issues/147

**Comment by XiXiaPdx** [comment] 2021-03-11 21:37
> I think this issue is a duplicate of this one: #147

I would prefer to keep this one as it has my notes from investigating the work needed to do this. How about I close #147 with a comment that the request is being tracked here instead?

**Comment by jasonjkeller** [comment] 2021-03-11 23:49
Sure, that's fine with me.

**Comment by jasonjkeller** [comment] 2021-04-13 21:17
The agent portion of this is done in this PR: https://github.com/newrelic/newrelic-java-agent/tree/jfr-service

The agent will pass its config to the daemon.

The daemon will handle setting the proxy in this PR: https://github.com/newrelic/newrelic-jfr-core/pull/178

**Closed** 2021-04-14 21:23 UTC
Labels: enhancement
